/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formulários;

/**
 *
 * @author saulo.geovane
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        txt_campocadastrocodigo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_cadastro = new javax.swing.JLabel();
        lbl_cadastronome = new javax.swing.JLabel();
        txt_campocadastronome = new javax.swing.JTextField();
        lbl_cadastrosexo = new javax.swing.JLabel();
        cbx_boxcadastrosexo = new javax.swing.JComboBox();
        lbl_cadastroocupacao = new javax.swing.JLabel();
        txt_campocadastroocupacao = new javax.swing.JTextField();
        btn_cadastrocancelar = new javax.swing.JButton();
        btn_cadastrosalvar = new javax.swing.JButton();
        btn_cadastronovo = new javax.swing.JButton();
        lbl_cadastroemail = new javax.swing.JLabel();
        txt_campocadastroemail = new javax.swing.JTextField();
        lbl_cadastrosenha = new javax.swing.JLabel();
        txt_campocadastrosenha = new javax.swing.JTextField();
        lbl_cadastroconfirmasenha = new javax.swing.JLabel();
        txt_campocadastroconfirmasenha = new javax.swing.JTextField();
        lbl_cadastrofamilia = new javax.swing.JLabel();
        txt_cadastrograuparentesco = new javax.swing.JTextField();
        lbl_cadastroparentesco = new javax.swing.JLabel();
        txt_campocadastrofamilia = new javax.swing.JTextField();
        lbl_cadastrocodigo = new javax.swing.JLabel();
        txt_campocadastrocodigo = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbl_cadastro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbl_cadastro.setText("CADASTRO");

        lbl_cadastronome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl_cadastronome.setText("NOME:");

        lbl_cadastrosexo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl_cadastrosexo.setText("SEXO:");

        cbx_boxcadastrosexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        cbx_boxcadastrosexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_boxcadastrosexoActionPerformed(evt);
            }
        });

        lbl_cadastroocupacao.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl_cadastroocupacao.setText("OCUPAÇÃO:");

        btn_cadastrocancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btn_cadastrocancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel-32.png"))); // NOI18N
        btn_cadastrocancelar.setText("CANCELAR");
        btn_cadastrocancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrocancelarActionPerformed(evt);
            }
        });

        btn_cadastrosalvar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btn_cadastrosalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save-32.png"))); // NOI18N
        btn_cadastrosalvar.setText("SALVAR");

        btn_cadastronovo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btn_cadastronovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add-User-32.png"))); // NOI18N
        btn_cadastronovo.setText("NOVO");

        lbl_cadastroemail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl_cadastroemail.setText("E-MAIL:");

        lbl_cadastrosenha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl_cadastrosenha.setText("SENHA:");

        lbl_cadastroconfirmasenha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl_cadastroconfirmasenha.setText("CONFIRMA SENHA: ");

        lbl_cadastrofamilia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lbl_cadastrofamilia.setText("FAMÍLIA:");

        lbl_cadastroparentesco.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        lbl_cadastroparentesco.setText("GRAU DE PARENTESCO:");

        lbl_cadastrocodigo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbl_cadastrocodigo.setText("CÓDIGO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_cadastroparentesco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cadastrograuparentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_cadastrocodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_campocadastrocodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_cadastrofamilia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_campocadastrofamilia))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_cadastroemail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_campocadastroemail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_cadastrosenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_campocadastrosenha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_cadastronome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_campocadastronome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_cadastrosexo)
                                .addGap(18, 18, 18)
                                .addComponent(cbx_boxcadastrosexo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_cadastroocupacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_campocadastroocupacao, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_cadastroconfirmasenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_campocadastroconfirmasenha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cadastronovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cadastrosalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cadastrocancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(lbl_cadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastrocodigo)
                    .addComponent(txt_campocadastrocodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastronome)
                    .addComponent(txt_campocadastronome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastrosexo)
                    .addComponent(cbx_boxcadastrosexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cadastroocupacao)
                    .addComponent(txt_campocadastroocupacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastrofamilia)
                    .addComponent(txt_campocadastrofamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastroparentesco)
                    .addComponent(txt_cadastrograuparentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastroemail)
                    .addComponent(txt_campocadastroemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_cadastrosenha)
                    .addComponent(txt_campocadastrosenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cadastroconfirmasenha)
                    .addComponent(txt_campocadastroconfirmasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastronovo)
                    .addComponent(btn_cadastrosalvar)
                    .addComponent(btn_cadastrocancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_boxcadastrosexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_boxcadastrosexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_boxcadastrosexoActionPerformed

    private void btn_cadastrocancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrocancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cadastrocancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrocancelar;
    private javax.swing.JButton btn_cadastronovo;
    private javax.swing.JButton btn_cadastrosalvar;
    private javax.swing.JComboBox cbx_boxcadastrosexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cadastro;
    private javax.swing.JLabel lbl_cadastrocodigo;
    private javax.swing.JLabel lbl_cadastroconfirmasenha;
    private javax.swing.JLabel lbl_cadastroemail;
    private javax.swing.JLabel lbl_cadastrofamilia;
    private javax.swing.JLabel lbl_cadastronome;
    private javax.swing.JLabel lbl_cadastroocupacao;
    private javax.swing.JLabel lbl_cadastroparentesco;
    private javax.swing.JLabel lbl_cadastrosenha;
    private javax.swing.JLabel lbl_cadastrosexo;
    private javax.swing.JTextField txt_cadastrograuparentesco;
    private javax.swing.JTextField txt_campocadastrocodigo;
    private javax.swing.JTextField txt_campocadastroconfirmasenha;
    private javax.swing.JTextField txt_campocadastroemail;
    private javax.swing.JTextField txt_campocadastrofamilia;
    private javax.swing.JTextField txt_campocadastronome;
    private javax.swing.JTextField txt_campocadastroocupacao;
    private javax.swing.JTextField txt_campocadastrosenha;
    // End of variables declaration//GEN-END:variables
}
